# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
# - gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- curl -sSL https://get.rvm.io | bash -s stable --ruby
- gem install cocoapods
- set -o pipefail && xcodebuild test -workspace Example/GreedKeyboardManager.xcworkspace -scheme GreedKeyboardManager-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint GreedKeyboardManager.podspec --verbose --use-libraries
